#todo 你的建表语句,包含索引
CREATE TABLE `ord_trade` (
                             `id` varchar(50) NOT NULL COMMENT '交易编号',
                             `pay_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '支付状态',
                             `payment_method` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付方式',
                             `delivery_method` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '配送方式',
                             `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价',
                             `flow_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总价格',
                             `freight_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
                             `discount_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠的金额',
                             `member_id` bigint NOT NULL COMMENT '买家id',
                             `member_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '买家用户名',
                             `member_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '买家用户手机号',
                             `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
                             `create_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建者',
                             `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                             `update_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '更新者',
                             `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                             `deleted` int NOT NULL DEFAULT '0' COMMENT '逻辑删除（0正常 1已删除）',
                             `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
                             PRIMARY KEY (`id`) USING BTREE,
                             KEY `idx_trade_userId` (`member_id`) COMMENT '用户编号索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='交易订单表';

CREATE TABLE `ord_order` (
                             `id` varchar(50) NOT NULL  COMMENT '订单编号',
                             `trade_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '交易编号 关联Trade',
                             `order_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '订单类型',
                             `promotion_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '促销类型 1：普通订单 2：赠品订单 3：拼团订单 4：积分订单 5：砍价订单',
                             `promotion_id` bigint DEFAULT NULL COMMENT '促销Id',
                             `distribution_id` bigint DEFAULT NULL COMMENT '分销商id',
                             `distribution_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分销员名称',
                             `distribution_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分销员手机号',
                             `pay_status` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '付款状态 1:待付款 2：已付款 3：已取消',
                             `payment_time` datetime(6) DEFAULT NULL COMMENT '支付时间',
                             `payment_method` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付方式',
                             `order_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '订单状态',
                             `goods_num` int NOT NULL DEFAULT '0' COMMENT '商品数量',
                             `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品价格',
                             `flow_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总价格',
                             `discount_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠的金额',
                             `coupon_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠券金额',
                             `freight_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
                             `weight` double(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单商品总重量',
                             `member_id` bigint NOT NULL COMMENT '买家Id',
                             `member_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '买家用户名',
                             `member_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '买家用户手机号',
                             `store_id` bigint NOT NULL COMMENT '店铺ID',
                             `store_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '店铺名称',
                             `logistics_code` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '物流公司CODE',
                             `logistics_name` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '物流公司名称',
                             `logistics_no` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '送货单号',
                             `logistics_time` datetime DEFAULT NULL COMMENT '送货时间',
                             `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
                             `verification_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '提货码',
                             `consignee_id` bigint DEFAULT NULL COMMENT '收件人Id',
                             `consignee_mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收件人手机',
                             `consignee_name` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收件人姓名',
                             `consignee_detail` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收件人详细地址',
                             `consignee_addr_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收件人地址编码 '',''分割',
                             `consignee_addr_path` varchar(200) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收件人地址名称  '',''分割"',
                             `shipper_id` bigint DEFAULT NULL COMMENT '发件人Id',
                             `shipper_mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '发件人电话',
                             `shipper_center` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '发件人经纬度',
                             `shipper_contacts` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '发件人联系人',
                             `shipper_addr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '发件人地址',
                             `client_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '订单来源',
                             `use_coupon_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户使用的优惠券Id,逗号隔开',
                             `show_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '是否显示 0：不显示 1：显示',
                             `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
                             `create_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建者',
                             `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                             `update_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '更新者',
                             `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                             `deleted` int NOT NULL DEFAULT '0' COMMENT '逻辑删除（0正常 1已删除）',
                             `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
                             PRIMARY KEY (`id`) USING BTREE,
                             KEY `idx_member_id` (`member_id`) COMMENT '会员id索引',
                             KEY `idx_store_id` (`store_id`) USING BTREE COMMENT '店铺id索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单表';

CREATE TABLE `ord_order_item` (
                                  `id` varchar(50) NOT NULL COMMENT '子订单编号',
                                  `trade_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '交易编号',
                                  `order_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单编号',
                                  `goods_id` bigint NOT NULL COMMENT '商品ID',
                                  `goods_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品编码',
                                  `goods_image` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '图片',
                                  `goods_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品名称',
                                  `goods_type` char(2) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '商品类型 1:实物商品',
                                  `goods_source_type` char(2) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '商品来源类型 1：平台 2：配送点',
                                  `sku_id` bigint NOT NULL COMMENT '货品ID',
                                  `num` int NOT NULL DEFAULT '0' COMMENT '购买量-销售量',
                                  `specs` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '规格json',
                                  `unit_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
                                  `flow_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实际金额',
                                  `goods_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '销售金额',
                                  `sub_total` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT '小记',
                                  `coupon_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠券金额',
                                  `freight_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
                                  `settle_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '结算金额',
                                  `after_sale_id` bigint DEFAULT NULL COMMENT '售后单Id',
                                  `after_sale_status` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '可申请售后状态',
                                  `after_sale_num` int NOT NULL DEFAULT '0' COMMENT '退货数量',
                                  `service_status` char(2) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '售后服务状态',
                                  `comment_status` varchar(2) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '评论状态',
                                  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
                                  `create_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建者',
                                  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                  `update_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '更新者',
                                  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                  `deleted` int NOT NULL DEFAULT '0' COMMENT '逻辑删除（0正常 1已删除）',
                                  `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
                                  PRIMARY KEY (`id`) USING BTREE,
                                  KEY `order_id` (`order_id`) USING BTREE COMMENT '订单编号索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='子订单表';

CREATE TABLE `ord_order_log` (
                                 `id` varchar(50) NOT NULL COMMENT '日志编号',
                                 `order_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单编号',
                                 `message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '日志信息',
                                 `order_status` char(2) COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单状态',
                                 `operator_id` bigint DEFAULT NULL COMMENT '操作者ID',
                                 `operator_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '操作者名称',
                                 `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户ID',
                                 `create_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建者',
                                 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                 `update_by` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '更新者',
                                 `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                 `deleted` int NOT NULL DEFAULT '0' COMMENT '逻辑删除（0正常 1已删除）',
                                 `remark` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
                                 PRIMARY KEY (`id`) USING BTREE,
                                 KEY `idx_order_id` (`order_id`) USING BTREE COMMENT '订单编号索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单日志表';



